name: tests

on:
  push:
    paths-ignore:
      - ".vscode/"
      - ".github/"
      - "cypress/"
      - ".vscode/"
      - "typed-scss-modules.config.ts"
      - "eslint.config.mjs"
      - "cypress.config.ts"
      - ".prettierrc"
      - ".gitignore"
      - "README.md"
      - "LICENSE"
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      NAME: ${{ vars.NAME }}
      SCHEME: ${{ vars.SCHEME }}
      HOST: ${{ vars.HOST }}
      PORT: ${{ vars.PORT }}
      DOMAIN: ${{ vars.DOMAIN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
      
      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm run tests:unit
